### PR TITLE
Redirect old /*-new/ URLs to the right place.

### PR DESCRIPTION
**Pull request by jankeromnes**
Examples from our logs:

```
[2018-07-24T08:16:47.030Z] 404 /projects-new/
[2018-07-24T08:16:47.649Z] 404 /about/
[2018-07-24T08:16:47.996Z] 404 /projects-new
[2018-07-24T08:16:51.123Z] 404 /reference/api-new/
[2018-07-24T08:16:51.510Z] blog
[2018-07-24T08:16:52.020Z] 404 /settings-new/
[2018-07-24T08:16:55.996Z] 404 /blog-new/
```

### CODE REVIEW

**Comment by jankeromnes** [comment]
Thanks @notriddle!

**Comment by jankeromnes** [comment]
Hm, I wonder if we shouldn't have edited the existing route RegExps to optionally support `-new`, because this approach won't work with sub-pages, nor will it keep query parameters or anchors (e.g. `/containers-new/?key=1234`, `/blog-new/#janitor-news-5`)

**Comment by notriddle** [comment]
What does the `?key` even do on containers-new?

**Comment by jankeromnes** [comment]
It's the login key from email URLs (but ok, it's a very unlikely example as we've never shared URLs like these).

**Pull request merged**
